spring.application.name=complain-managment
spring.datasource.url=jdbc:mysql://localhost:3306/complaintdb
spring.datasource.username=root
spring.datasource.password=shanu24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080